FROM continuumio/miniconda3:4.7.12-alpine

USER root

# Always use the local requirements.txt to override the cloned one
COPY requirements.txt /requirements.txt

ENV PATH=$PATH:/opt/conda/bin

#configure aws; will be used for dvc
RUN aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID \
  && aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY \
  && aws configure set default.region $AWS_REGION

RUN mkdir -p /app/continuous-intelligence \
  && apk --no-cache add git nano bash \
  && git clone https://github.com/KeeBac/cd4ml-workshop-2.git /app/continuous-intelligence \
  && mv /requirements.txt /app/continuous-intelligence/requirements.txt \
  && cd /app/continuous-intelligence \
  && pip install --no-cache-dir --no-compile -r requirements.txt \
  && conda list && conda clean -tipy \
  && dvc repro model.pkl.dvc \
  && dvc push model.pkl.dvc \
  && git add model.pkl.dvc \
  && git commit -m 'model updated' \
  && git push https://KeeBac:1fc0014de83c2dfa06c6c039aa9c2cc36a2f74b1@github.com/KeeBac/cd4ml-workshop-2.git

