FROM continuumio/miniconda3:4.7.12-alpine

USER root

# declare args
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_REGION
ARG GIT_USER
ARG GIT_TOKEN

# set env variables to be accessed by the shell script
ENV AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
ENV AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
ENV AWS_REGION=${AWS_REGION}
ENV GIT_USER=${GIT_USER}
ENV GIT_TOKEN=${GIT_TOKEN}

# Always use the local requirements.txt to override the cloned one
COPY requirements.txt /requirements.txt

ENV PATH=$PATH:/opt/conda/bin

RUN mkdir -p /app/continuous-intelligence \
  && apk --no-cache add git nano bash \
  && git clone https://github.com/KeeBac/cd4ml-workshop-2.git /app/continuous-intelligence \
  && mv /requirements.txt /app/continuous-intelligence/requirements.txt \
  && cd /app/continuous-intelligence \
  && pip install --no-cache-dir --no-compile -r requirements.txt \
  && conda list && conda clean -tipy

CMD ["/app/continuous-intelligence/ml_pipeline.sh"]
